### ISSUE TITLE
branches to folders error

### ISSUE THREAD

**Issue by jmoeyersons** [IBCNServices/ghtt#8]
![Screenshot 2023-05-15 at 10 29 44](https://github.com/IBCNServices/ghtt/assets/15744141/95c6d65f-382e-4fd5-95cf-960dca3562e6)

Branches-to-folder command can interrupt when there are untracked files. Maybe add the `--force` option or similar in the script?

**Comment by merlijn-sebrechts** [comment]
This might be fixed in the latest version: we don't use "git checkout" anymore in branches-to-folders so it shouldn't give that error anymore, I think. Please let me know if this is not the case.
